.TH "Crate" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrate\fP (\fBVector3D\fP pos, \fBModel3D\fP &model, \fBGameData\fP &data)"
.br
.ti -1c
.RI "\fBCrate\fP (const \fBCrate\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBCrate\fP (\fBCrate\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBCrate\fP & \fBoperator=\fP (const \fBCrate\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBCrate\fP & \fBoperator=\fP (\fBCrate\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "void \fBUpdate\fP () final"
.br
.ti -1c
.RI "void \fBdropItem\fP ()"
.br
.ti -1c
.RI "void \fBOnCollisionEnter\fP (std::unique_ptr< \fBEntity\fP > &other) noexcept final"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameData\fP & \fBdata_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Crate::Crate (\fBVector3D\fP pos, \fBModel3D\fP & newModel, \fBGameData\fP & data)"
It creates a crate entity, adds a transform, a renderer and a box collider to it, and sets the transform's position, scale and rotation
.PP
\fBParameters\fP
.RS 4
\fIpos\fP The position of the crate\&. 
.br
\fInewModel\fP The model to be used for the crate\&. 
.br
\fIdata\fP The \fBGameData\fP object, which is used to get the model of the crate\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Crate::dropItem ()"
If the random number generator returns a number that is not 0, then the function returns\&. Otherwise, it adds an item to the game world
.PP
\fBReturns\fP
.RS 4
A reference to the data_ member\&. 
.RE
.PP

.SS "void Crate::OnCollisionEnter (std::unique_ptr< \fBEntity\fP > & other)\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
If the crate collides with a wall, destroy the crate
.PP
\fBParameters\fP
.RS 4
\fIother\fP The entity that collided with this entity\&. 
.RE
.PP

.PP
Implements \fBEntity\fP\&.
.SS "void Crate::Update ()\fC [final]\fP, \fC [virtual]\fP"
If the crate is enabled, do nothing
.PP
\fBReturns\fP
.RS 4
Nothing\&. 
.RE
.PP

.PP
Implements \fBEntity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
