.TH "Plane" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plane
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlane\fP (const \fBPlane\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBPlane\fP (\fBPlane\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBPlane\fP & \fBoperator=\fP (const \fBPlane\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBPlane\fP & \fBoperator=\fP (\fBPlane\fP &&rhs) noexcept=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdraw\fP (\fBVector3D\fP pos, \fBVector2D\fP size, std::array< unsigned char, 3 > color) noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Plane::draw (\fBVector3D\fP pos, \fBVector2D\fP size, std::array< unsigned char, 3 > color)\fC [static]\fP, \fC [noexcept]\fP"
Draws a plane at the specified position, with the specified size and color
.PP
\fBParameters\fP
.RS 4
\fIpos\fP The position of the plane\&. 
.br
\fIsize\fP The size of the plane\&. 
.br
\fIcolor\fP The color of the plane\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
