.TH "Scene" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP (const \fBScene\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBScene\fP (\fBScene\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBScene\fP & \fBoperator=\fP (const \fBScene\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBScene\fP & \fBoperator=\fP (\fBScene\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "virtual void \fBaction\fP () noexcept=0"
.br
.ti -1c
.RI "virtual \fBColorManager\fP \fBgetBackgroundColor\fP () const noexcept=0"
.br
.ti -1c
.RI "virtual void \fBswitchAction\fP () noexcept=0"
.br
.ti -1c
.RI "virtual void \fBplayMusic\fP () noexcept=0"
.br
.ti -1c
.RI "virtual void \fBupdateMusic\fP () const noexcept=0"
.br
.ti -1c
.RI "virtual void \fBSystemDestroy\fP () noexcept=0"
.br
.ti -1c
.RI "virtual void \fBSystemCollision\fP () noexcept=0"
.br
.ti -1c
.RI "virtual void \fBSystemDisplay\fP () noexcept=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Scene::action ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "virtual \fBColorManager\fP Scene::getBackgroundColor () const\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "virtual void Scene::playMusic ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "virtual void Scene::switchAction ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "virtual void Scene::SystemCollision ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP\&.
.SS "virtual void Scene::SystemDestroy ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP\&.
.SS "virtual void Scene::SystemDisplay ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.
.SS "virtual void Scene::updateMusic () const\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBGame\fP, \fBHome\fP, \fBLoad\fP, \fBPlayerSelect\fP, and \fBSplash\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
