.TH "Wall" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wall
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWall\fP (\fBVector3D\fP pos, \fBModel3D\fP &model)"
.br
.ti -1c
.RI "\fBWall\fP (const \fBWall\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBWall\fP (\fBWall\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBWall\fP & \fBoperator=\fP (const \fBWall\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBWall\fP & \fBoperator=\fP (\fBWall\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "void \fBUpdate\fP () final"
.br
.ti -1c
.RI "void \fBOnCollisionEnter\fP (std::unique_ptr< \fBEntity\fP > &other) noexcept final"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Wall::Wall (\fBVector3D\fP pos, \fBModel3D\fP & model)"
It creates a wall entity with a transform, a renderer and a box collider
.PP
\fBParameters\fP
.RS 4
\fIpos\fP The position of the wall 
.br
\fImodel\fP The model to be used for the wall\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Wall::OnCollisionEnter (std::unique_ptr< \fBEntity\fP > & other)\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
If the entity colliding with this wall is another wall, and the position of this wall is greater than 0, destroy the other wall
.PP
\fBParameters\fP
.RS 4
\fIother\fP The entity that collided with this entity\&. 
.RE
.PP

.PP
Implements \fBEntity\fP\&.
.SS "void Wall::Update ()\fC [final]\fP, \fC [virtual]\fP"
If the wall is enabled, move it down by 4 units per frame
.PP
\fBReturns\fP
.RS 4
The return type is a pointer to a \fBComponent\fP\&. 
.RE
.PP

.PP
Implements \fBEntity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
