.TH "AI" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAI\fP (\fBAI\fP const &other) noexcept=default"
.br
.ti -1c
.RI "\fBAI\fP (\fBAI\fP &&other) noexcept=default"
.br
.ti -1c
.RI "\fBAI\fP & \fBoperator=\fP (\fBAI\fP const &other) noexcept=default"
.br
.ti -1c
.RI "\fBAI\fP & \fBoperator=\fP (\fBAI\fP &&other) noexcept=default"
.br
.ti -1c
.RI "ComponentType \fBgetComponentType\fP () const noexcept"
.br
.ti -1c
.RI "AIEvent \fBgetEvent\fP (Vector2 &playerPosition, std::vector< \fBVector3D\fP > &boxes, std::vector< \fBVector3D\fP > &bombs, std::vector< \fBVector3D\fP > &fires, std::vector< \fBVector3D\fP > &players, std::vector< \fBVector3D\fP > &powerups, int nbBomb)"
.br
.ti -1c
.RI "void \fBhandleColliding\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr ComponentType \fBTYPE\fP = ComponentType::AI"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ComponentType AI::getComponentType () const\fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
