.TH "AWindow" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBWindowManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAWindow\fP (int width, int height, int fps) noexcept"
.br
.ti -1c
.RI "\fBAWindow\fP (const \fBAWindow\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBAWindow\fP (\fBAWindow\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBAWindow\fP & \fBoperator=\fP (const \fBAWindow\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBAWindow\fP & \fBoperator=\fP (\fBAWindow\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "int \fBgetWidth\fP () const noexcept"
.br
.ti -1c
.RI "int \fBgetHeight\fP () const noexcept"
.br
.ti -1c
.RI "float \fBgetFps\fP () const noexcept"
.br
.ti -1c
.RI "virtual void \fBsetFps\fP (float value) noexcept=0"
.br
.ti -1c
.RI "virtual void \fBresetHeight\fP () noexcept=0"
.br
.ti -1c
.RI "virtual void \fBresetWidth\fP () noexcept=0"
.br
.ti -1c
.RI "virtual bool \fBisExit\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth_\fP"
.br
.ti -1c
.RI "int \fBheight_\fP"
.br
.ti -1c
.RI "float \fBfps_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AWindow::AWindow (int width, int height, int fps)\fC [noexcept]\fP"
It's a constructor for the \fBAWindow\fP class
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP The width of the window in pixels\&. 
.br
\fIheight\fP The height of the window in pixels\&. 
.br
\fIfps\fP The number of frames per second\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "float AWindow::getFps () const\fC [noexcept]\fP"
It returns the value of the private member variable fps_\&.
.PP
\fBReturns\fP
.RS 4
The fps_ variable\&. 
.RE
.PP

.SS "int AWindow::getHeight () const\fC [noexcept]\fP"
This function returns the height of the window\&.
.PP
\fBReturns\fP
.RS 4
The height of the window\&. 
.RE
.PP

.SS "int AWindow::getWidth () const\fC [noexcept]\fP"
This function returns the width of the window\&.
.PP
\fBReturns\fP
.RS 4
The width of the window\&. 
.RE
.PP

.SS "virtual bool AWindow::isExit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBWindowManager\fP\&.
.SS "virtual void AWindow::resetHeight ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBWindowManager\fP\&.
.SS "virtual void AWindow::resetWidth ()\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBWindowManager\fP\&.
.SS "virtual void AWindow::setFps (float value)\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBWindowManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
