.TH "Controller" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBController\fP (const \fBController\fP &other) noexcept=default"
.br
.ti -1c
.RI "\fBController\fP (\fBController\fP &&other) noexcept=default"
.br
.ti -1c
.RI "\fBController\fP & \fBoperator=\fP (const \fBController\fP &rhs) noexcept=default"
.br
.ti -1c
.RI "\fBController\fP & \fBoperator=\fP (\fBController\fP &&rhs) noexcept=default"
.br
.ti -1c
.RI "bool \fBisKeyDown\fP (const Key &key) const noexcept"
.br
.ti -1c
.RI "bool \fBisKeyPressed\fP (const Key &key) const noexcept"
.br
.ti -1c
.RI "bool \fBisGamepadConnected\fP (int id) const noexcept"
.br
.ti -1c
.RI "bool \fBisGamepadButtonPressed\fP (int id, const G_Button &button) const noexcept"
.br
.ti -1c
.RI "float \fBgetGamepadAxis\fP (int id, const Axis &axis) const noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "float Controller::getGamepadAxis (int id, const Axis & axis) const\fC [noexcept]\fP"
It returns the value of the specified axis of the specified gamepad
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID of the gamepad to check\&. 
.br
\fIaxis\fP The axis to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
The value of the axis\&. 
.RE
.PP

.SS "bool Controller::isGamepadButtonPressed (int id, const G_Button & button) const\fC [noexcept]\fP"
It returns true if the specified gamepad button is pressed
.PP
\fBParameters\fP
.RS 4
\fIid\fP The id of the gamepad to check\&. 
.br
\fIbutton\fP The button to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
A boolean value\&. 
.RE
.PP

.SS "bool Controller::isGamepadConnected (int id) const\fC [noexcept]\fP"
It returns true if the gamepad is connected, false otherwise
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID of the gamepad to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
A boolean value\&. 
.RE
.PP

.SS "bool Controller::isKeyDown (const Key & key) const\fC [noexcept]\fP"
It returns true if the specified key is currently pressed down
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
A boolean value\&. 
.RE
.PP

.SS "bool Controller::isKeyPressed (const Key & key) const\fC [noexcept]\fP"
If the key is pressed, return true, otherwise return false
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
A boolean value\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
