.TH "Entity" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBomb\fP, \fBCrate\fP, \fBFire\fP, \fBItem\fP, \fBPlayer\fP, and \fBWall\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntity\fP (const \fBEntity\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBEntity\fP (\fBEntity\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBEntity\fP & \fBoperator=\fP (const \fBEntity\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBEntity\fP & \fBoperator=\fP (\fBEntity\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBOnCollisionEnter\fP (std::unique_ptr< \fBEntity\fP > &other) noexcept=0"
.br
.ti -1c
.RI "template<typename T > void \fBaddComponent\fP (const T &component) noexcept"
.br
.ti -1c
.RI "std::vector< std::unique_ptr< \fBComponent\fP > > & \fBgetComponents\fP () noexcept"
.br
.ti -1c
.RI "template<typename T > std::optional< std::reference_wrapper< T > > \fBgetComponent\fP () noexcept"
.br
.ti -1c
.RI "bool \fBgetEnabledValue\fP () const noexcept"
.br
.ti -1c
.RI "void \fBdestroy\fP () noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void Entity::OnCollisionEnter (std::unique_ptr< \fBEntity\fP > & other)\fC [pure virtual]\fP, \fC [noexcept]\fP"

.PP
Implemented in \fBFire\fP, \fBItem\fP, \fBPlayer\fP, \fBBomb\fP, \fBCrate\fP, and \fBWall\fP\&.
.SS "virtual void Entity::Update ()\fC [pure virtual]\fP"

.PP
Implemented in \fBBomb\fP, \fBCrate\fP, \fBFire\fP, \fBItem\fP, \fBPlayer\fP, and \fBWall\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
