.TH "Game" 3 "Wed Jun 15 2022" "Version 1.0" "Indie Studio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBScene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGame\fP (\fBCore\fP &core_ref) noexcept"
.br
.ti -1c
.RI "\fBGame\fP (const \fBGame\fP &other) noexcept=delete"
.br
.ti -1c
.RI "\fBGame\fP (\fBGame\fP &&other) noexcept=delete"
.br
.ti -1c
.RI "\fBGame\fP & \fBoperator=\fP (const \fBGame\fP &rhs) noexcept=delete"
.br
.ti -1c
.RI "\fBGame\fP & \fBoperator=\fP (\fBGame\fP &&rhs) noexcept=delete"
.br
.ti -1c
.RI "void \fBaction\fP () noexcept final"
.br
.ti -1c
.RI "void \fBplayMusic\fP () noexcept final"
.br
.ti -1c
.RI "void \fBupdateMusic\fP () const noexcept final"
.br
.ti -1c
.RI "\fBColorManager\fP \fBgetBackgroundColor\fP () const noexcept final"
.br
.ti -1c
.RI "void \fBswitchAction\fP () noexcept final"
.br
.ti -1c
.RI "void \fBSystemDestroy\fP () noexcept final"
.br
.ti -1c
.RI "void \fBSystemCollision\fP () noexcept final"
.br
.ti -1c
.RI "void \fBSystemDisplay\fP () noexcept final"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::Game (\fBCore\fP & core_ref)\fC [noexcept]\fP"
It initializes the game scene
.PP
\fBParameters\fP
.RS 4
\fIcore_ref\fP a reference to the core of the game 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Game::action ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It updates the game
.PP
\fBReturns\fP
.RS 4
The return type is void\&. 
.RE
.PP

.PP
Implements \fBScene\fP\&.
.SS "\fBColorManager\fP Game::getBackgroundColor () const\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It returns the background color of the game
.PP
\fBReturns\fP
.RS 4
A reference to the background color\&. 
.RE
.PP

.PP
Implements \fBScene\fP\&.
.SS "void Game::playMusic ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It plays the music 
.PP
Implements \fBScene\fP\&.
.SS "void Game::switchAction ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It resets the game
.PP
\fBReturns\fP
.RS 4
The return type is void\&. 
.RE
.PP

.PP
Implements \fBScene\fP\&.
.SS "void Game::SystemCollision ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
For every entity, check if it's colliding with any other entity 
.PP
Implements \fBScene\fP\&.
.SS "void Game::SystemDestroy ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
If an entity is disabled, remove it from the entity list 
.PP
Implements \fBScene\fP\&.
.SS "void Game::SystemDisplay ()\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It displays the game 
.PP
Implements \fBScene\fP\&.
.SS "void Game::updateMusic () const\fC [final]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"
It updates the music 
.PP
Implements \fBScene\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Indie Studio from the source code\&.
